name: 'Update Image Tag Go'
description: 'Updates the image tag in a YAML file using Go and the GitHub API'
branding:
  icon: 'info'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  REPO_NAME:
    description: 'Repository name'
    required: true
  FILE_PATH:
    description: 'Path to the YAML file'
    required: true
  IMAGE_TAG:
    description: 'The new image tag'
    required: true
  REPO_OWNER:
    description: 'Repository Owner'
    required: true
  GITHUB_BRANCH:
    description: 'Github Branch'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'